### ISSUE TITLE
When debug=true, works. Once set debug=false, server gives error

### ISSUE THREAD

**Issue by HuangHam** [nivlab/nivturk#104] opened 2022-09-20 19:19 UTC
The error is something like can't find the consent form. Why is this happening? I'm using nivturk prolific.

**Comment by szorowi1** [comment] 2022-09-20 19:22
Hi @HuangHam, can you copy/paste the error Flask is giving you?

**Comment by szorowi1** [comment] 2022-09-27 13:55
Hi @HuangHam, I am going to close this issue for now as I was unable to reproduce the problem as reported. If you're continuing to run into a problem, feel free to reopen this issue.

**Closed as completed by szorowi1** 2022-09-27 13:55 UTC
